services:
  - type: web
    name: ocr-image-to-text
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --no-cache-dir -r requirements.txt
      mkdir -p uploads
    startCommand: gunicorn app:app
    envVars:
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
